Class1 data
nathanhbsimmons/javascript-workbook pull request #1
Opened 2018-01-20 19:10 UTC by nathanhbsimmons

added final solutions

2018-01-22 18:46 UTC, reneemeyer requested changes
Nathan, nice job on the PR and the assignment, just a couple things to fix before you merge.

2018-01-22 18:46 UTC, reneedudley commented on 01week/datatypes.js
> +typeof
this would throw an error, why is it here?

2018-01-22 18:46 UTC, reneedudley commented on 01week/datatypes.js
> +  if((arg1 || arg2) && !(arg1 && arg2)){
the second part `!(arg1 && arg2)` is redundant and not needed

2018-01-23 20:25 UTC, nathanhbsimmons reviewed
Suggested changes made

2018-01-24 01:09 UTC, merged